<script setup lang="ts">
</script>

<template>
  <CodeTree
    default-value="manifest.config.ts"
    title="crxjs-svelte"
  >
    <ImageDisplay
      url="/vanilla-ts/public/logo.png"
      alt-text="crx_logo"
      filename="public/logo.png"
    />
    <ImageDisplay
      url="/vanilla-ts/src/assets/crx.svg"
      alt-text="crx_logo"
      filename="src/assets/crx.svg"
    />
    <ImageDisplay
      url="/svelte-ts/src/assets/svelte.svg"
      alt-text="svelte_logo"
      filename="src/assets/svelte.svg"
    />
    <ImageDisplay
      url="/vanilla-ts/src/assets/vite.svg"
      alt-text="vite_logo"
      filename="src/assets/vite.svg"
    />

    <CodeSnippet
      url="/svelte-ts/src/components/HelloWorld.svelte"
      language="svelte"
      filename="src/components/HelloWorld.svelte"
    />

    <CodeSnippet
      url="/svelte-ts/src/content/views/App.svelte"
      language="svelte"
      filename="src/content/views/App.svelte"
    />
    <CodeSnippet
      url="/svelte-ts/src/content/main.ts"
      language="ts"
      filename="src/content/main.ts"
    />

    <CodeSnippet
      url="/svelte-ts/src/popup/App.svelte"
      language="svelte"
      filename="src/popup/App.svelte"
    />
    <CodeSnippet
      url="/svelte-ts/src/popup/index.html"
      language="html"
      filename="src/popup/index.html"
    />
    <CodeSnippet
      url="/svelte-ts/src/popup/main.ts"
      language="ts"
      filename="src/popup/main.ts"
    />
    <CodeSnippet
      url="/svelte-ts/src/popup/style.css"
      language="css"
      filename="src/popup/style.css"
    />

    <CodeSnippet
      url="/vanilla-ts/manifest.config.ts"
      language="ts"
      filename="manifest.config.ts"
    />
    <CodeSnippet
      url="/svelte-ts/package.json"
      language="json"
      filename="package.json"
    />
    <CodeSnippet
      url="/svelte-ts/tsconfig.json"
      language="json"
      filename="tsconfig.json"
    />
    <CodeSnippet
      url="/svelte-ts/vite.config.ts"
      language="ts"
      filename="vite.config.ts"
    />
  </CodeTree>
</template>
